openapi: 3.0.0
x-origin:
  - url: http://localhost:5000/swagger/doc.json
    format: swagger
    version: "2.0"
    converter:
      url: https://github.com/mermade/oas-kit
      version: 7.0.8
info:
  description: This is a sample server.
  title: Swagger Example API
  termsOfService: http://localhost:6000/terms/
  contact:
    name: API Support
    url: http://www.localhost:6000/support
    email: support@localhost:6000
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  version: "1.0"
paths:
  /api/v1/users:
    get:
      description: Get all Users
      tags:
        - users
      summary: Get all Users
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/models.User"
        "500":
          description: Internal Server Error
          content:
            application/json:
              schema:
                type: string
    put:
      description: Update User By Email
      tags:
        - users
      summary: Update User By Email
      parameters:
        - description: Email
          name: email
          in: path
          required: true
          schema:
            type: string
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/models.User"
        description: User
        required: true
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/models.User"
        "500":
          description: Internal Server Error
          content:
            application/json:
              schema:
                type: string
    post:
      description: Create User
      tags:
        - users
      summary: Create User
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/models.User"
        "500":
          description: Internal Server Error
          content:
            application/json:
              schema:
                type: string
  /api/v1/users/check-password:
    post:
      description: Check User Password. Rate limited by IP for 3 requests per 30 minutes.
      tags:
        - users
      summary: Check User Password
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/authentication.UserAuth"
        description: UserAuth
        required: true
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                type: string
        "400":
          description: Bad Request
          content:
            application/json:
              schema:
                type: string
        "429":
          description: Too Many Requests
          content:
            application/json:
              schema:
                type: string
  "/api/v1/users/{email}":
    get:
      description: Find User By Email
      tags:
        - users
      summary: Find User By Email
      parameters:
        - description: Email
          name: email
          in: path
          required: true
          schema:
            type: string
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/models.User"
        "500":
          description: Internal Server Error
          content:
            application/json:
              schema:
                type: string
components:
  schemas:
    authentication.UserAuth:
      type: object
      required:
        - password
        - username
      properties:
        password:
          type: string
        scope:
          type: string
        username:
          type: string
    models.User:
      type: object
      required:
        - email
        - name
        - password
      properties:
        created_at:
          type: string
        email:
          type: string
        id:
          type: string
        name:
          type: string
        password:
          type: string
        updated_at:
          type: string
